ProyectoIntegrador_AdopcionMascotas/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using ProyectoIntegrador_AdopcionMascotas.Models;
using Dominio.Entidades;
using Dominio.Repositorio;

namespace ProyectoIntegrador_AdopcionMascotas.Controllers
{
    public class AnimalController : Controller
    {
        //BD_SISTEMA_ADOPCIONEntities bd = new BD_SISTEMA_ADOPCIONEntities();

        Animal_BL a_bl = new Animal_BL();

        RazaAnimal_BL r_bl = new RazaAnimal_BL();

        public string nombreimg(long codigo)
        {

            if (1 <= codigo && codigo < 10) return "img00000" + codigo;
            else
            {
                if (10 <= codigo && codigo < 100) return "img0000" + codigo;
                else
                {
                    if (100 <= codigo && codigo < 1000) return "img000" + codigo;
                    else
                    {
                        if (1000 <= codigo && codigo < 10000) return "img00" + codigo;
                        else
                        {
                            if (10000 <= codigo && codigo < 100000) return "img0" + codigo;
                            else return "img" + codigo;
                        }
                    }
                }
            }

        }



        // GET: Animal
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Detalle(long codigo)
        {


            //return View(bd.SP_DETALLE_ANIMAL().Where(x => x.CODANIMAL == codigo).FirstOrDefault());

            Animal_Tuneado at = a_bl.detalle(codigo);
            return View(at);
        }

        public ActionResult ElegirTipo()
        {
            if (Session["Usuario"] == null) {
                Session["next_page"] = new string[] {"RA","0"};
                return RedirectToAction("Logueo", "Logueo");
            } 
            Usuario u = (Usuario)Session["Usuario"];
            ViewBag.dueño = u.CODUSUARIO;
            return View();

        }

        public ActionResult Registrar(long tIPO, long dUEÑO)
        {

            SelectList cboRaza = new SelectList(r_bl.lista(tIPO), "CODRAZA", "DESC_RAZA");

            //SelectList cboRaza = new SelectList(bd.RAZAANIMAL.Where(x => x.CODTIPO == tIPO).OrderBy(x => x.DESC_RAZA).ToList(), "CODRAZA", "DESC_RAZA");
            ViewBag.razas = cboRaza;
            return View(new Animal(tIPO, dUEÑO));
        }

        [HttpPost]
        public ActionResult Registrar(Animal a, HttpPostedFileBase archivo)
        {
            string msg;

            SelectList cboRaza = new SelectList(r_bl.lista(a.TIPO), "CODRAZA", "DESC_RAZA", a.RAZA);
            //SelectList cboRaza = new SelectList(bd.RAZAANIMAL.Where(x => x.CODTIPO == a.TIPO).OrderBy(x => x.DESC_RAZA).ToList(), "CODRAZA", "DESC_RAZA", a.RAZAANIMAL);


            if (ModelState.IsValid == false)
            {
                ViewBag.razas = cboRaza;
                return View(a);
            }

            if (a.EDAD == null) a.EDAD = 0;
            if (a.PESO == null) a.PESO = 0;
            if (a.DESCRIPCION == null) a.DESCRIPCION = "";


            if (archivo == null) {
                a.FOTO = "-";
                msg = a_bl.registrar(a);
            
            }else
            {
                bool p = Path.GetExtension(archivo.FileName) == ".jpg";
                bool q = Path.GetExtension(archivo.FileName) == ".png";
                bool r = Path.GetExtension(archivo.FileName) == ".gif";


                //si el archivo no es jpg, png o gif
                if (!p && !q && !r)
                {
                    ViewBag.ext_invalida = "Debe seleccionar una imagen en formato jpg,png o gif";
                    ViewBag.razas = cboRaza;
                    return View(a);
                }


                try
                {
                    string foto = nombreimg(a_bl.cod_autogenerado()) + Path.GetExtension(archivo.FileName);

                    archivo.SaveAs(Server.MapPath("~/imagenes/animales/" + foto));

                    a.FOTO = foto;
                    
                    msg = a_bl.registrar(a);
                }
                catch (Exception e)
                {
                    msg = "Error: " + e.Message;

                }

            }
            

            ViewBag.razas = cboRaza;
            return RedirectToAction("ConfirmarOperacion", "Confirmacion", new { mensaje = msg });

        }


        public ActionResult Editar(long codanimal) {
            
            Animal a = a_bl.listaAnimales().Where(x => x.CODANIMAL == codanimal).FirstOrDefault();
            SelectList cboRaza = new SelectList(r_bl.lista(a.TIPO), "CODRAZA", "DESC_RAZA");
            ViewBag.razas = cboRaza;
            return View(a);
        }

        [HttpPost]
        public ActionResult Editar(Animal a, HttpPostedFileBase archivo) {

            string msg;

            SelectList cboRaza = new SelectList(r_bl.lista(a.TIPO), "CODRAZA", "DESC_RAZA", a.RAZA);
            //SelectList cboRaza = new SelectList(bd.RAZAANIMAL.Where(x => x.CODTIPO == a.TIPO).OrderBy(x => x.DESC_RAZA).ToList(), "CODRAZA", "DESC_RAZA", a.RAZAANIMAL);


            if (ModelState.IsValid == false)
            {
                ViewBag.razas = cboRaza;
                return View(a);
            }

            if (a.EDAD == null) a.EDAD = 0;
            if (a.PESO == null) a.PESO = 0;
            if (a.DESCRIPCION == null) a.DESCRIPCION = "";


            if (archivo == null)
            {
       
                msg = a_bl.editar(a);

            }
            else
            {
                bool p = Path.GetExtension(archivo.FileName) == ".jpg";
                bool q = Path.GetExtension(archivo.FileName) == ".png";
                bool r = Path.GetExtension(archivo.FileName) == ".gif";


                //si el archivo no es jpg, png o gif
                if (!p && !q && !r)
                {
                    ViewBag.ext_invalida = "Debe seleccionar una imagen en formato jpg,png o gif";
                    ViewBag.razas = cboRaza;
                    return View(a);
                }


                try
                {
                    string foto = nombreimg(a.CODANIMAL) + Path.GetExtension(archivo.FileName);

                    archivo.SaveAs(Server.MapPath("~/imagenes/animales/" + foto));

                    a.FOTO = foto;

                    msg = a_bl.editar(a);
                }
                catch (Exception e)
                {
                    msg = "Error: " + e.Message;

                }

            }


            ViewBag.razas = cboRaza;
            return RedirectToAction("ConfirmarOperacion", "Confirmacion", new { mensaje = msg });
        }

    }
}

ProyectoIntegrador_AdopcionMascotas/Controllers/InteresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dominio.Entidades;
using Dominio.Repositorio;

namespace ProyectoIntegrador_AdopcionMascotas.Controllers
{
    public class InteresController : Controller
    {
        Interes_BL i_bl = new Interes_BL();

        public ActionResult Registrar(long animal)
        {
            if (Session["Usuario"] == null)
            {
                Session["next_page"] = new string[] { "RI",animal+"" };
                return RedirectToAction("Logueo", "Logueo");
            }
            Usuario u = (Usuario)Session["Usuario"];
            string msg;
            msg = i_bl.registrar(animal, u.CODUSUARIO);
            return RedirectToAction("ConfirmarOperacion","Confirmacion",new { mensaje=msg});
        }


        public ActionResult Listar(long codanimal) {
            
            return View(i_bl.listar(codanimal));
        }
    }
}

ProyectoIntegrador_AdopcionMascotas/Controllers/PerfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dominio.Entidades;
using Dominio.Repositorio;

namespace ProyectoIntegrador_AdopcionMascotas.Controllers
{
    public class PerfilController : Controller
    {

        Usuario_BL u_bl = new Usuario_BL();
        Animal_BL a_bl = new Animal_BL();
        

        public ActionResult Detalle()
        {
            Usuario u_sesion = (Usuario)Session["Usuario"];
            Usuario_Tuneado ut = u_bl.lista().Where(x => x.CODUSUARIO == u_sesion.CODUSUARIO).FirstOrDefault();
            return View(ut);
        }

        public ActionResult Editar() {

            Usuario u_sesion = (Usuario)Session["Usuario"];

            return View(u_sesion);

        }

        [HttpPost]
        public ActionResult Editar(Usuario u)
        {
            string msg;

            if (ModelState.IsValid == false) return View(u);
            if (u.EMAIL == null) u.EMAIL = "";
            if (u.TELEFONO == null) u.TELEFONO = "";
            if (u.FOTO == null) u.FOTO = "";

            msg = u_bl.editar(u);


            return RedirectToAction("ConfirmarOperacion", "Confirmacion", new { mensaje = msg });

        }


        public ActionResult Anadidas() {

            Usuario u_sesion = (Usuario)Session["Usuario"];
            return View(a_bl.mis_mascotas_anadidas(u_sesion.CODUSUARIO));
        }

        public ActionResult Favoritas() {
            Usuario u_sesion = (Usuario)Session["Usuario"];
            return View(a_bl.mis_mascotas_favoritas(u_sesion.CODUSUARIO));
        }

    }
}

ProyectoIntegrador_AdopcionMascotas/Views/Perfil/Anadidas.cshtml
@model IEnumerable<Dominio.Entidades.Animal_Tuneado>

@{
    ViewBag.Title = "Mis mascotas añadidas";
    Layout = "~/Views/Shared/_LayoutPerfil.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Registrar nueva mascota", "ElegirTipo","Animal")
</p>


<section class="seccionArticulos">

    @foreach (var item in Model)
    {
    <article class="articulo">

        <a href="@Url.Action("Detalle","Animal",new { codigo = item.CODANIMAL })">

            <img class="imgart" src=@Url.Content(string.Format("~/imagenes/animales/{0}",item.FOTO.ToLower())) alt="Imagen no disponible" />

        </a>
        <p class="parrart">@Html.DisplayFor(modelItem => item.NOMBRE), @Html.DisplayFor(modelItem => item.SEXO), @Html.DisplayFor(modelItem => item.TAMAÑO) </p>  
        @Html.ActionLink("Editar Datos", "Editar", "Animal", new { codanimal = item.CODANIMAL },null) <br />
        @Html.ActionLink("Ver Interesados", "Listar", "Interes", new { codanimal = item.CODANIMAL },null) 
    </article>

    }

</section>





     

ProyectoIntegrador_AdopcionMascotas/Views/Perfil/Detalle.cshtml
@model Dominio.Entidades.Usuario_Tuneado

@{
    ViewBag.Title = "Mis Datos";
    Layout = "~/Views/Shared/_LayoutPerfil.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CODUSUARIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CODUSUARIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NOMBRES)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOMBRES)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FEC_NAC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FEC_NAC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DNI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DNI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SEXO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SEXO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DIRECCION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIRECCION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMAIL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TELEFONO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TELEFONO)
        </dd>    

        <dt>
            @Html.DisplayNameFor(model => model.ESTADO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ESTADO)
        </dd>

    </dl>
</div>

ProyectoIntegrador_AdopcionMascotas/Views/Perfil/Editar.cshtml
@model Dominio.Entidades.Usuario

@{
    ViewBag.Title = "Editando mis datos personales";
    Layout = "~/Views/Shared/_LayoutPerfil.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />

    @Html.HiddenFor(model => model.CODUSUARIO)

    @Html.HiddenFor(model => model.NOMBRES)

    @Html.HiddenFor(model => model.APELLIDOS)

    @Html.HiddenFor(model => model.FEC_NAC)

    @Html.HiddenFor(model => model.DNI)

    @Html.HiddenFor(model => model.SEXO)

    @Html.HiddenFor(model => model.ESTADO)

    @Html.HiddenFor(model => model.FOTO)

    <div class="form-group">
        @Html.LabelFor(model => model.DIRECCION, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DIRECCION, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DIRECCION, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TELEFONO, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TELEFONO, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TELEFONO, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IDLOGIN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IDLOGIN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IDLOGIN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PASS, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PASS, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PASS, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="GUARDAR CAMBIOS" class="btn btn-default" />
        </div>
    </div>
</div>
}

ProyectoIntegrador_AdopcionMascotas/Views/Perfil/Favoritas.cshtml
@model IEnumerable<Dominio.Entidades.Animal_Tuneado>

@{
    ViewBag.Title = "Mis mascotas favoritas";
    Layout = "~/Views/Shared/_LayoutPerfil.cshtml";
}

<h2>@ViewBag.Title</h2>

<section class="seccionArticulos">

    @foreach (var item in Model)
    {
        <article class="articulo">

            <a href="@Url.Action("Detalle","Animal",new { codigo = item.CODANIMAL })">

                <img class="imgart" src=@Url.Content(string.Format("~/imagenes/animales/{0}",item.FOTO.ToLower())) alt="Imagen no disponible" />

            </a>
            <p class="parrart">@Html.DisplayFor(modelItem => item.NOMBRE), @Html.DisplayFor(modelItem => item.SEXO), @Html.DisplayFor(modelItem => item.TAMAÑO) </p>
            
        </article>

    }

</section>